import HomeComponent from "@/components/Home/home";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Home Page",
  description: "Generated by create next app",
};

export default function HomePage() {
  return <HomeComponent />;
}
