import ProfileComponent from "@/components/Profile/profile";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Profile Page",
  description: "Generated by create next app",
};

export default function ProfilePage() {
  return <ProfileComponent />;
}
