import RegisterComponent from "@/components/Register/register";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Register Page",
  description: "Generated by create next app",
};

export default function RegisterPage() {
  return <RegisterComponent />;
}
